Controllers/BlogFolderSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using PruebaUmbracoComposition.Web.ViewModel;
using Umbraco.Web;
using Umbraco.Web.PublishedModels;

namespace PruebaUmbracoComposition.Web.Controllers
{
    public class BlogFolderSurfaceController : SurfaceController
    {
         public ActionResult BlogItemList(int Id)
        {
            var blogFolderNode = Umbraco.Content(Id) as BlogFolder;
            var blogItems = blogFolderNode.Children<BlogItem>();

            var BlogFoldervm = new BlogFolderViewModel();
            BlogFoldervm.BlogFTitle = blogFolderNode.BFtitle;
            BlogFoldervm.Lista = blogItems.OrderBy(i=>i.BlogTitle);

            return PartialView(BlogFoldervm);
        }
    }
}

Controllers/HeroBannerSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedModels;
using PruebaUmbracoComposition.Web.ViewModel;
using Umbraco.Web;
using Umbraco.Core.Models;

namespace PruebaUmbracoComposition.Web.Controllers
{
    public class HeroBannerSurfaceController : SurfaceController
    {
        
        public ActionResult HeroBannerImage(int Id)
        {
            //primero probe de poner as Home pero esta partial solo me servia para recuperar la imagen de la composition que esta en Home
            //var homeNode = Umbraco.Content(Id) as Home;

            //luego probe no poner ningun as y me resulto ok, por ahora.....
            var node = Umbraco.Content(Id);

           
            //var imageHeroBanner = homeNode.HeroBannerIimage;
            //var titleHeroBanner = homeNode.HeroBannerTitle;
            //var subtitleHeroBanner = homeNode.HeroBannerSubtitle;

            var imageHeroBanner = node.Value<MediaWithCrops>("HeroBannerIimage");
            var titleHeroBanner = node.Value<string>("HeroBannerTitle");
            var subtitleHeroBanner = node.Value<string>("HeroBannerSubtitle");

            var heroBannerVm = new HeroBannerViewModel();

            //OJO: no me funcionan las comprobaciones String
            if(String.IsNullOrEmpty(titleHeroBanner))
            {
                heroBannerVm.HeroTitle = "Default Title";
              
            }
            else
            {
                heroBannerVm.HeroTitle = titleHeroBanner;
            }
           

            if(!String.IsNullOrEmpty(subtitleHeroBanner) )
            {
                heroBannerVm.HeroSubtitle = subtitleHeroBanner;
            }
            else
            {
                heroBannerVm.HeroSubtitle = "Default Subtitle";
            }
           

            if (imageHeroBanner != null)
            {
                heroBannerVm.HeroImageUrl = imageHeroBanner.Url();
            }
            else
            {
                heroBannerVm.HeroImageUrl = "/Images/pexels-burst-374906.jpg";
            }


            return PartialView(heroBannerVm);
        }
    }
}

Controllers/HeroDesdeHomeSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.PublishedModels;
using PruebaUmbracoComposition.Web.ViewModel;
using Umbraco.Web;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models.PublishedContent;

namespace PruebaUmbracoComposition.Web.Controllers
{
    public class HeroDesdeHomeSurfaceController : SurfaceController
    {
        
        public ActionResult GetHeroDesdeHome(int Id)
        {
            //obtengo el contenido de la pagina actual por el id que me pasa al llamar al renderAction
            var contentNode = Umbraco.Content(Id);
            //obtengo el root de esa pagina que en este caso es Home
            var home = contentNode.Root() as Home;
            //recupero los campos de Home qu me interesa recuperar
            IPublishedContent heroImage = home.GetProperty("heroBannerHomePropertyImage")?.GetValue() as IPublishedContent;
            String heroTitle = home.GetProperty("heroBannerHomePropertyTitle")?.GetValue() as String;
            String heroSubtitle = home.GetProperty("heroBannerHomePropertySubtitle")?.GetValue() as String;
            var imgUrl = heroImage.Url();

            //instancio mi viewModel que me cree
            //le doy los valores que recupere del contenido publicado a cada una de sus propiedades
            GetHeroDesdeHomeViewModel heroBannerDesdeHomeVM = new GetHeroDesdeHomeViewModel();
            heroBannerDesdeHomeVM.HeroTitleDesdeHome = heroTitle;
            heroBannerDesdeHomeVM.HeroSubtitleDesdeHome = heroSubtitle;
            heroBannerDesdeHomeVM.HeroImageUrlDesdeHome = imgUrl;

            //devuelto la partialView con mismo nombre que metodo ActionResult y paso parametro a la partial con valores llenos
            return PartialView(heroBannerDesdeHomeVM);
        }
    }
}

Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.About>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "Master.cshtml";
}
@{Html.RenderAction("HeroBannerImage", "HeroBannerSurface", new { Id = Model.Id }); }

<h1>@Model.Value("aboutTitle")</h1>

<p>@Model.Value("pageContentText")</p>

@Html.GetGridHtml(Model, "us", "Bootstrap3")

Views/AboutGrid.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.AboutDosGrid>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = "Master.cshtml";
}

@Html.GetGridHtml(Model,"aboutDosGridProperty","Bootstrap3")

@if(@Model.Value("aboutDosTexto")!=null){

    <div><p>@Model.Value("aboutDosTexto")</p></div>
}

Views/AboutTresDesdeHome.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.AboutTresDesdeHome>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "Master.cshtml";

}



@{Html.RenderAction("GetHeroDesdeHome", "HeroDesdeHomeSurface", new { Id = Model.Id }); }

<div>
    <p>
        @if (Model.AboutTresText != null)
        {

            @Model.AboutTresText;
        }

    </p>
</div>

Views/BlogFolder.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.BlogFolder>
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Core.PropertyEditors.ValueConverters;
@{
    Layout = "Master.cshtml";
}



@{Html.RenderAction("BlogItemList", "BlogFolderSurface", new { Id = Model.Id }); }

Views/BlogItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.BlogItem>
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Core.PropertyEditors.ValueConverters;
@{
    Layout = "Master.cshtml";

    var imgCropper = Model.Value<ImageCropperValue>("BlogImage");
    var imgUrl = imgCropper.Src;
    var mainUrl = imgUrl + imgCropper.GetCropUrl("Main");

}


<article class="container">
    <header class="text-center">
        <div class="row">
            <div class="col">
                <h1>@Model.BlogTitle</h1>
                <div>
                    <ul style="list-style: none">
                        <li>
                            <i class="fa fa-user"></i> by @Model.BlogAuthor
                        </li>
                        <li>
                            <i class="fa fa-calendar"></i>@Model.BlogPostDate.ToString("dd-MMM-yyyy")
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
               

                <img src="@mainUrl" class="w-100" />
            </div>
        </div>
    </header>

    <div class="row">
        <div class="col">
            <p>@Model.BlogText</p>
        </div>
    </div>

    <footer>
        <div class="row">
            <div class="col">
                <div><span>Author: <strong>@Model.BlogAuthor</strong></span></div>
                <div><span>Categories: @string.Join(", ", Model.BlogItemCategories)</span></div>
            </div>
        </div>

    </footer>
</article>

Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Home>
@using ContentModels = Umbraco.Web.PublishedModels;


@{ Layout = "Master.cshtml";
    var imgUrl = "";

    if (Model.HeroBannerHomePropertyImage!= null)

    {
        imgUrl = Model.HeroBannerHomePropertyImage.Url();


    }

}

@*@{Html.RenderAction("HeroBannerImage", "HeroBannerSurface", new {Id = Model.Id }); }*@


<div class="jumbotron jumbotron-fluid home-hero" style="background-image:url(@imgUrl)">
    <div class="inner">
        <div class="container">
            <h1 class="display-4">@Model.HeroBannerHomePropertyTitle</h1>
            <p class="lead">@Model.HeroBannerHomePropertySubtitle</p>
        </div>
    </div>
</div>



@Html.Partial("CallToAction")

<h1>@Model.Value("tituloHome")</h1>

<p>@Model.Value("textoDeHome")</p>

<p>@Model.Value("pageContentText")</p>



@Html.Partial("LastestItems")

Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using ClientDependency.Core.Mvc
@{
    Layout = null;
   
}

<html>
<head>
    <!-- Scripts, css que traigo de las web-->
    @{
        Html.RequiresCss("https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css", new
        {
            integrity = "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm",
            crossorigin = "anonymous"
        });
        Html.RequiresCss("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css");





        Html.RequiresJs("https://code.jquery.com/jquery-3.2.1.slim.min.js",
        new
        {
            integrity = "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN",
            crossorigin = "anonymous"
        });

        Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js",
        new
        {
            integrity = "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q",
            crossorigin = "anonymous"
        });


        Html.RequiresJs("https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js",
        new
        {
            integrity = "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl",
            crossorigin = "anonymous"
        });

        Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js");


       
        Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js");

        Html.RequiresJs("https://cdnjs.cloudflare.com/ajax/libs/jquery-validate-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js");


      


    }
    <!--aqui va el css-->
    @Html.RenderCssHere()

</head>
<body>
    <!--NavBar-->
    @Html.Partial("Navegador")

    @*@Html.Partial("Hero")*@

    @RenderBody()

    <!--footer-->
    @Html.Partial("Footer")
    <!--aqui va el js-->
    @Html.RenderJsHere()
</body>


</html>

Views/Partials/BlockList/Default.cshtml
@inherits UmbracoViewPage<BlockListModel>
@using Umbraco.Core.Models.Blocks
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;
        @Html.Partial("BlockList/Components/" + data.ContentType.Alias, block)        
    }
</div>

Views/Partials/BlogItemList.cshtml
@model PruebaUmbracoComposition.Web.ViewModel.BlogFolderViewModel
<h1>@Model.BlogFTitle</h1>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="container">
                <div class="row">
                    <div class="col">
                        @foreach (var item in Model.Lista)
                        {
                            var imgCropper = item.BlogImage;
                            var imgUrl = imgCropper.Src;
                            var smallUrl = imgUrl + imgCropper.GetCropUrl("Small");

                            <div class="card mt-25 mb-25">
                                <a class="text-decoration-none" href="@item.Url()">
                                    <div class="card">
                                        <div>
                                            <img src="@smallUrl" />
                                        </div>
                                        <div class="card-body">
                                            <h4 class="card-title">@item.BlogTitle</h4>
                                        </div>
                                    </div>
                                </a>
                            </div>

                        }

                    </div>
                </div>
            </div>

        </div>



    </div>
</div>

Views/Partials/CallToAction.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Umbraco.Web.Models
<section class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col text-center py-5">
                <h1 class="display-4">@Model.Value("callToActionTitle")</h1>
                <p class="lead">@Model.Value("callToActionText")</p>
                <!-- Link  para el call to action. codigo que umbraco recomienda usar con el multipicker-->
                @{
                    var link = Model.Value<Link>("callToActionLink");
                    if (link != null)
                    {
                        <a href="@link.Url" target="@link.Target" class="btn btn-outline-secondary">@link.Name</a>
                    }
                }
            </div>
        </div>
    </div>
</section>

Views/Partials/Footer.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
<footer class="bg-dark">
    <div class="container">
        <div class="row">
            <div class="col text-center py-4">
                <ul class="list-inline-item">
                    <li class="list-inline-item">
                        <a href="https://twitter.com/hdeveloped" target="_blank" title="Follow us on twitter">
                            <i class="fab fa-twitter fa-2x text-white"></i>
                        </a>
                    </li>
                </ul>
                <p class="text-white">Copyright &copy; @DateTime.Now.Year My Page</p>
            </div>
        </div>
    </div>
</footer>

Views/Partials/GetHeroDesdeHome.cshtml
@model PruebaUmbracoComposition.Web.ViewModel.GetHeroDesdeHomeViewModel

<div class="jumbotron jumbotron-fluid home-hero" style="background-image:url('@Model.HeroImageUrlDesdeHome')">
    <div class="inner">
        <div class="container">
            <h1 class="display-4">@Model.HeroTitleDesdeHome</h1>
            <p class="lead">@Model.HeroSubtitleDesdeHome</p>
        </div>
    </div>
</div>

Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@*
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.GetType() == typeof(JObject) && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row)
                    }
                </div>
            }
        }else {
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row)
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.GetType() == typeof(JObject) && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true)
                    }
                </div>
            }
        }else {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false)
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @if (singleColumn) {
            @:<div class="container">
        }
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @if (singleColumn) {
            @:</div>
        }
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Views/Partials/Grid/Editors/DocTypeGridEditor/heroBanner.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HeroBannerGridEditor>
@using ContentModels = Umbraco.Web.PublishedModels;

  @{
      var imgUrl="";
      var title="";
      var subtitle = "";



   }
      @if (!String.IsNullOrEmpty(Model.HeroBannerGridEditorTitle))
      {
          title = Model.HeroBannerGridEditorTitle;
      }

@if (!String.IsNullOrEmpty(Model.HeroBannerGridEditorSubtitle))
{
    subtitle = Model.HeroBannerGridEditorSubtitle;
}

@if (Model.HeroBannerGridEditorImage != null)
{
   imgUrl = Model.HeroBannerGridEditorImage.Url();


}

<div class="jumbotron jumbotron-fluid home-hero" style="background-image:url(@imgUrl)">
    <div class="inner">
        <div class="container">
            <h1 class="display-4">@title</h1>
            <p class="lead">@subtitle</p>
        </div>
    </div>
</div>

Views/Partials/Grid/Editors/DocTypeGridEditor/us.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Us>
@using ContentModels = Umbraco.Web.PublishedModels;

@if (!String.IsNullOrEmpty(Model.UsTitle)) 
{ 
    <div>@Model.UsTitle</div>

}

@if (Model.UsText!=null) 
{
    <div>
        <p>@Model.UsText</p>
    </div>
}

@if (Model.UsImage != null) 
{
   
        var imgUrl = Model.UsImage.Url();
    
    <div>
        <img src="@imgUrl" width="500" />
    </div>

}

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@{
    string embedValue = Convert.ToString(Model.value);
    embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;
}

<div class="video-wrapper">
	@Html.Raw(embedValue)
</div>

Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Core.PropertyEditors.ValueConverters

@if (Model.value != null)
{
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        if (Model.value.coordinates != null)
        {
            url = ImageCropperTemplateExtensions.GetCropUrl(
                (string)url,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropAlias: "default",
                cropDataSet: new ImageCropperValue
                {
                    Crops = new[]
                    {
                        new ImageCropperValue.ImageCropperCrop
                        {
                            Alias = "default",
                            Coordinates = new ImageCropperValue.ImageCropperCropCoordinates
                            {
                                X1 = (decimal)Model.value.coordinates.x1,
                                Y1 = (decimal)Model.value.coordinates.y1,
                                X2 = (decimal)Model.value.coordinates.x2,
                                Y2 = (decimal)Model.value.coordinates.y2
                            }
                        }
                    }
                });
        }
        else
        {
            url = ImageCropperTemplateExtensions.GetCropUrl(
                (string)url,
                width: (int)Model.editor.config.size.width,
                height: (int)Model.editor.config.size.height,
                cropDataSet: new ImageCropperValue
                {
                    FocalPoint = new ImageCropperValue.ImageCropperFocalPoint
                    {
                        Top = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.top,
                        Left = Model.value.focalPoint == null ? 0.5m : Model.value.focalPoint.left
                    }
                });
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;

    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates
@{
    var htmlLocalLinkParser = Current.Factory.GetInstance<HtmlLocalLinkParser>();
    var htmlUrlParser = Current.Factory.GetInstance<HtmlUrlParser>();
    var htmlImageSourceParser = Current.Factory.GetInstance<HtmlImageSourceParser>();

    var value = htmlLocalLinkParser.EnsureInternalLinks(Model.value.ToString());
    value = htmlUrlParser.EnsureUrls(value);
    value = htmlImageSourceParser.EnsureImageSources(value);
}
@Html.Raw(value)

Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaks((string)Model.value.ToString()).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

Views/Partials/Hero.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Umbraco.Web.Models
@*<div class="jumbotron jumbotron-fluid home-hero" style="background-image:url('/Images/pexels-burst-374906.jpg')">*@
<div class="jumbotron jumbotron-fluid home-hero" style="background-image:url('')">
    <div class="inner">
        <div class="container">
            <h1 class="display-4">Title</h1>
            <p class="lead">Subtitle</p>
        </div>
    </div>
</div>

Views/Partials/HeroBannerImage.cshtml
@model PruebaUmbracoComposition.Web.ViewModel.HeroBannerViewModel


<div class="jumbotron jumbotron-fluid home-hero" style="background-image:url('@Model.HeroImageUrl')">
    <div class="inner">
        <div class="container">
            <h1 class="display-4">@Model.HeroTitle</h1>
            <p class="lead">@Model.HeroSubtitle</p>
        </div>
    </div>
</div>

Views/Partials/Prueba.cshtml
@model PruebaUmbracoComposition.Web.ViewModel.PruebaViewModel